const SAGA_TYPE = {
  UPDATE_TASK_STATUS: 'UPDATE_TASK_STATUS',
  FETCH_TASKS: 'FETCH_TASKS',
  EDIT_TASK: 'EDIT_TASK',
  FETCH_TASK: 'FETCH_TASK',
  ADD_TASK: 'ADD_TASK',
};

export default SAGA_TYPE;
